# Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/config.yml

change-nametag-prefix-suffix: true
change-tablist-prefix-suffix: true
enable-header-footer: true

header:
  - "&8&m                                        &r"
  - ""
  - "&5&lAbyssGN &8| &dSeason I"
  - "&7&oAbyssGN.minehut.gg"
  - ""
footer:
  - ""
  - "&d%ping%MS &8// &d%online% Player(s) &8// &d%tps%TPS"
  - "&7&oAbyssGN.craftingstore.net"
  - ""
  - "&8&m                                        &r"

yellow-number-in-tablist: ""
group-sorting-priority-list:
  - owner
  - admin
  - mod
  - opal
  - jade
  - ruby
  - topaz
  - amber
  - default

Groups:
  _OTHER_:
    tabprefix: "%vault-prefix%"
    tagprefix: "%vault-prefix%"
    tabsuffix: "%vault-suffix%%afk%"
    tagsuffix: "%vault-suffix%%afk%"
    customtabname: "%essentialsnick%"
    customtagname: "%essentialsnick%"

Users: {}

classic-vanilla-belowname:
  enabled: false
  number: " "
  text: " "

enable-collision: false
revert-collision-rule-in-worlds:
  - revertedworld
do-not-move-spectators: false
allow-spectator-bypass-permission: false
unlimited-nametag-prefix-suffix-mode:
  enabled: false
  modify-npc-names: false
  use-marker-tag-for-1-8-x-clients: false

per-world-settings:
  world1:
    header:
      - "an example of world with custom"
    footer:
      - "header/footer and prefix/suffix"
    Groups:
      Owner:
        tabprefix: "&0&l[&a&lOwner&0&l] &a"
        tagprefix: "&2&lOwner &a"
  world2-world3:
    header:
      - "This is a shared header for"
      - "world2 and world3"
placeholders:
  afk-yes: " &5&l[AFK]"
  afk-no: ""
  date-format: "dd.MM.yyyy"
  time-format: "[HH:mm:ss / h:mm a]"
  time-offset: 0
  remove-strings:
    - "[]"
    - "< >"
rank-aliases: {}
  
disable-features-in-worlds: {}

placeholderapi-refresh-intervals:
  default-refresh-interval: 100
  server:
    "%server_uptime%": 1000
    "%server_tps_1_colored%": 1000
  player:
    "%player_health%": 200
    "%player_ping%": 1000
    "%vault_prefix%": 1000
  relational:
    "%rel_factionsuuid_relation_color%": 500